newmatik/eso-erpnext

erpnext/hr/doctype/training_event/training_event.js
on_post_load function is addition all parent Employees.
Newmatik app needs only Employees with certain conditions to be added
using a custom btn.
For https://github.com/newmatik/Newmatik/issues/261
=> Remove on_post_load function

erpnext/stock/dashboard/item_dashboard_list.html, erpnext/stock/doctype/batch/batch.js
https://github.com/newmatik/Newmatik/issues/302
https://github.com/newmatik/Newmatik/issues/302
=> Remove hard codeed dashboard actions

erpnext/selling/doctype/sales_order_item/sales_order_item.json
=> Requested By column in Sales Order Item

erpnext/manufacturing/doctype/bom/bom.js
For: https://github.com/newmatik/Newmatik/issues/616
=> Add Item Group in BOM Item on item_code selection

erpnext/manufacturing/doctype/bom/bom.py
Please read the pull request checklist to make sure your changes are merged: https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist
=> Fix alternative items fetch when Work Order required items is called

erpnext/manufacturing/doctype/bom/alternative_items_selector.html, erpnext/manufacturing/doctype/bom/bom.js
More in https://github.com/newmatik/Newmatik/issues/1244
with newmatik update.
=> Allow Alternative Item update after submit

erpnext/manufacturing/doctype/work_order/work_order_dashboard.py
Removed as core change and added via script
=> Removed Traceability Log from WO dashboard

erpnext/hooks.py, erpnext/templates/pages/customer_provided_item.html, erpnext/templates/pages/customer_provided_item.py
=> Customer provided items web view

erpnext/manufacturing/doctype/bom/bom.js
=> feat(BOM): Add quantity in selected items

erpnext/stock/doctype/stock_entry/stock_entry.py
As suggested by Dominik removing feed to improve speed and reduce database clutter
=> refactor(stock-entry): Remove Feed

erpnext/controllers/accounts_controller.py
=> feat(PI): Access zero quantity to Purchase Invoice

erpnext/manufacturing/doctype/blanket_order_item/blanket_order_item.json
Cannot be done by Customize Form since it is a standard field.
Part of https://github.com/newmatik/Newmatik/issues/1396
=> refactor(blanket-order): Allow to change rate on submit

erpnext/manufacturing/doctype/bom/bom.py, erpnext/stock/stock_ledger.py
=> chore(py3): Indentation fixes

erpnext/buying/doctype/purchase_order/purchase_order_list.js, erpnext/controllers/status_updater.py
re: https://github.com/newmatik/newmatik/issues/2107
=> fix(PO): Status updater fix

erpnext/stock/doctype/material_request/material_request.js
Re: https://github.com/newmatik/newmatik/issues/2270
=> fix(Material Request): Fix "Stop" button error

erpnext/accounts/doctype/sales_invoice/sales_invoice.json, erpnext/selling/doctype/quotation/quotation.json, erpnext/selling/doctype/sales_order/sales_order.json
Re: 
This PR is to change `Allow on Submit` value to `true` for `Payment Terms Template`, `Payment Schedule`, and `Due Date` on `Sales Invoice`. This will make the https://github.com/newmatik/newmatik/pull/2297 PR to work.
=> fix(sales_invoice.json): Make fields allowable on submit

erpnext/manufacturing/doctype/bom/bom.py, erpnext/manufacturing/doctype/bom_item/bom_item.json
https://github.com/newmatik/newmatik/issues/2304
=> fix(alternative): Fix alternative setting in BOM and WO

erpnext/stock/doctype/stock_entry/stock_entry_utils.py
re: https://github.com/newmatik/newmatik/issues/2373
=> feat(Stock Entry): Add stock entry source

erpnext/accounts/doctype/sales_invoice/sales_invoice.json
re: https://github.com/newmatik/newmatik/issues/2457
=> fix(Sales Invoice): Filter fix

erpnext/stock/doctype/item/item.json
https://github.com/newmatik/newmatik/issues/2533
This is the easiest fix.
=> refactor(Item): Make Supplier Item no-copy upon duplicate

erpnext/selling/doctype/quotation/quotation.py
re: https://github.com/newmatik/newmatik/issues/2577
=> fix(Quotation): Set status Expired if not Lost

erpnext/crm/doctype/lead/lead.js, erpnext/crm/doctype/lead/lead.json, erpnext/crm/doctype/lead/lead.py
=> refactor(Lead): Changes to allow import of address

erpnext/crm/doctype/lead/lead.json, erpnext/crm/doctype/lead/lead.py
Sent a same PR to core https://github.com/frappe/erpnext/pull/21180
=> fix: Mandatory field missing to create address from lead

erpnext/crm/doctype/lead/lead.json
Please read the pull request checklist to make sure your changes are merged: https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist
=> fix: Set depends_on for address type in lead

erpnext/buying/doctype/purchase_order/purchase_order.json
https://github.com/newmatik/newmatik/issues/3062#issuecomment-628519151
=> refactor(po): Make po item Updatable on Submit

erpnext/selling/doctype/sales_order/sales_order.json
https://github.com/newmatik/newmatik/issues/3080
=> refactor(SO): Make So Item table allowable on submit

erpnext/controllers/accounts_controller.py, erpnext/public/js/utils.js
https://github.com/newmatik/newmatik/issues/3185
Had to custom in CORE since this is a core feature and the field is our custom.
=> fix(SO): Add required_by date in Update Items

erpnext/stock/doctype/item/item.json
Re: https://github.com/newmatik/newmatik/issues/3133#issuecomment-655824986
Forgot to PR this with the last one.
=> fix(item): rearrange supplier details section

erpnext/hr/doctype/leave_allocation/leave_allocation.json, erpnext/hr/doctype/leave_application/leave_application.py
https://github.com/newmatik/newmatik/issues/2758
=> refactor(LA): Allow update Leae Allocation

erpnext/stock/doctype/shipment/api/utils.py, erpnext/stock/doctype/shipment/shipment.js, erpnext/stock/doctype/shipment/shipment.json, erpnext/stock/doctype/shipment/shipment.py, erpnext/stock/doctype/shipment/shipment_list.js, erpnext/stock/doctype/shipment/shipment_service_selector.html, erpnext/stock/doctype/shipment/test_shipment.py, erpnext/stock/doctype/shipment_delivery_notes/shipment_delivery_notes.json, erpnext/stock/doctype/shipment_delivery_notes/shipment_delivery_notes.py, erpnext/stock/doctype/shipment_notification_subscriptions/shipment_notification_subscriptions.json, erpnext/stock/doctype/shipment_notification_subscriptions/shipment_notification_subscriptions.py, erpnext/stock/doctype/shipment_parcel/shipment_parcel.json, erpnext/stock/doctype/shipment_parcel/shipment_parcel.py, erpnext/stock/doctype/shipment_parcel_template/shipment_parcel_template.js, erpnext/stock/doctype/shipment_parcel_template/shipment_parcel_template.json, erpnext/stock/doctype/shipment_parcel_template/shipment_parcel_template.py, erpnext/stock/doctype/shipment_parcel_template/test_shipment_parcel_template.py, erpnext/stock/doctype/shipment_status_update_subscriptions/shipment_status_update_subscriptions.json, erpnext/stock/doctype/shipment_status_update_subscriptions/shipment_status_update_subscriptions.py
Re: https://github.com/newmatik/shipment/issues/98
This PR includes:
- Migrated shipment doctypes
- Removal of parcel service integration from the code as we will create a new erpnext integration for them.
=> feat(shipment): migrate shipment doctype into core

erpnext/stock/doctype/parcel_service/parcel_service.js, erpnext/stock/doctype/parcel_service/parcel_service.json, erpnext/stock/doctype/parcel_service/parcel_service.py, erpnext/stock/doctype/parcel_service/test_parcel_service.py, erpnext/stock/doctype/parcel_service_type/parcel_service_type.js, erpnext/stock/doctype/parcel_service_type/parcel_service_type.json, erpnext/stock/doctype/parcel_service_type/parcel_service_type.py, erpnext/stock/doctype/parcel_service_type/test_parcel_service_type.py, erpnext/stock/doctype/parcel_service_type_alias/parcel_service_type_alias.json, erpnext/stock/doctype/parcel_service_type_alias/parcel_service_type_alias.py
Forgot to add these doctypes on my initial PR. Migrated from newmatik to core.
Put these inside `Stock` module.
- Parcel Service
- Parcel Service Type
- Parcel Service Type Alias
=> feat(Parcel Service): initialize parcel service doctypes

erpnext/stock/doctype/shipment/shipment.json
re https://github.com/newmatik/shipment/issues/103
=> feat(Shipment): show incoterm

erpnext/stock/doctype/parcel_service_type/parcel_service_type.py, erpnext/stock/doctype/shipment/shipment.js, erpnext/stock/doctype/shipment/shipment.py
re https://github.com/newmatik/shipment/issues/97
=> feat(Shipment): integration of Packlink and LetMeShip

erpnext/stock/doctype/shipment/shipment.js, erpnext/stock/doctype/shipment/shipment.py
This PR includes:
- Change spaces to tabs
- Remove letmeship specific fields from the util functions (`get_company_contact ` and `get_contact `)
=> refactor(shipment): remove specific fields from util functions

erpnext/stock/doctype/delivery_note/delivery_note.js, erpnext/stock/doctype/delivery_note/delivery_note.py
Re: https://github.com/newmatik/shipment/issues/105
=> feat(DN): Create shipment from DN

erpnext/assets/doctype/asset/asset.py
re: https://github.com/newmatik/newmatik/issues/3334
=> refactor(Asset): Remove Purchase Amount validation

erpnext/assets/doctype/asset/asset.py
re: https://github.com/newmatik/newmatik/issues/3334#issuecomment-668345454
=> refactor(Asset): Ignore mandatory validations

erpnext/stock/doctype/shipment/test_shipment.py
re https://github.com/newmatik/shipment/issues/100
Updated from https://github.com/newmatik/erpnext/pull/86
=> feat(Shipment): unit test

erpnext/erpnext_integrations/doctype/letmeship/letmeship.js, erpnext/erpnext_integrations/doctype/letmeship/letmeship.json, erpnext/erpnext_integrations/doctype/letmeship/letmeship.py, erpnext/erpnext_integrations/doctype/letmeship/test_letmeship.py, erpnext/erpnext_integrations/doctype/packlink/packlink.js, erpnext/erpnext_integrations/doctype/packlink/packlink.json, erpnext/erpnext_integrations/doctype/packlink/packlink.py, erpnext/erpnext_integrations/doctype/packlink/test_packlink.py, erpnext/erpnext_integrations/utils.py, erpnext/stock/doctype/shipment/shipment.py
Re: https://github.com/newmatik/shipment/issues/97#issuecomment-669028305
Still works the same as before.
=> fix(packlink, letmeship): change module to erpnext integration

erpnext/erpnext_integrations/doctype/sendcloud/sendcloud.js, erpnext/erpnext_integrations/doctype/sendcloud/sendcloud.json, erpnext/erpnext_integrations/doctype/sendcloud/sendcloud.py, erpnext/erpnext_integrations/doctype/sendcloud/test_sendcloud.py, erpnext/stock/doctype/shipment/shipment.js, erpnext/stock/doctype/shipment/shipment.py
Re: https://github.com/newmatik/shipment/issues/110
The same functionality with this PR https://github.com/newmatik/shipment/pull/109
@creamdory we can squash the commits after this PR has been merged.
=> feat(sendcloud): add sendcloud integration to shipment

erpnext/manufacturing/doctype/bom_item/bom_item.json
https://github.com/newmatik/newmatik/issues/1244
=> refactor(BOM): Allow adding/changing of alternative

erpnext/manufacturing/doctype/work_order_item/work_order_item.json
https://github.com/newmatik/newmatik/issues/1243
=> refactor(WO): Allow switching alternative after Submit

erpnext/selling/doctype/quotation/quotation.json
https://github.com/newmatik/newmatik/issues/3538
=> fix(Quotation): Table Multiselect option fix

erpnext/public/js/utils.js
https://github.com/newmatik/newmatik/issues/3551
=> fix(SO,PO): Add qty and hide conversion in list view

erpnext/stock/get_item_details.py
https://github.com/newmatik/newmatik/issues/3616
=> fix(SO): Filter closed BO in item details

erpnext/controllers/accounts_controller.py, erpnext/public/js/utils.js
Re: https://github.com/newmatik/newmatik/issues/3618
Similar code with https://github.com/newmatik/erpnext/commit/f661d66c28c97d0ed80ee1c277b3b4c7938f36ca
This PR is for our own customization.
=> feat(accounts_controller): add update child qty and rate to BO

erpnext/manufacturing/doctype/blanket_order/blanket_order.json
Info is here https://github.com/newmatik/newmatik/pull/3661#issue-525750193
=> fix(Blanket Order): Fix update error

erpnext/hr/doctype/leave_application/leave_application.py
re: https://github.com/newmatik/newmatik/issues/3699
Also fixed in latest version of erpnext
=> fix(Leave Application): Do not create Leave Ledger on update

erpnext/manufacturing/doctype/work_order/work_order.json
Require for https://github.com/newmatik/newmatik/issues/3706
=> fix(WO): Allow to change WIP warehouse on submit

erpnext/stock/doctype/warehouse/warehouse_tree.js
re: https://github.com/newmatik/newmatik/issues/3850
=> fix(Warehouse tree): Round the amounts to 2 decimals

erpnext/hr/doctype/leave_allocation/leave_allocation.py
Related to https://github.com/newmatik/newmatik/issues/3798#issuecomment-768889412
Removing this, refactored it, and put it in custom hooks.
=> fix(Leave Allocation): Remove custom code

erpnext/stock/doctype/material_request/material_request.py
re: https://github.com/newmatik/newmatik/issues/4055
=> fix(MR): Remove over delivery validation

erpnext/stock/doctype/stock_entry/stock_entry.py
Remove validation which require to accept in the same warehouse as in material request.
Required for https://github.com/newmatik/newmatik/issues/4001
=> refactor(IGT): Allow accepting in different warehouse

erpnext/manufacturing/doctype/work_order/work_order.py
Required for https://github.com/newmatik/next/issues/1298
=> fix(WO): Remove hardcoded status setting

erpnext/selling/doctype/sales_order_item/sales_order_item.json
re: https://github.com/elexess/eso-newmatik/issues/4467#issuecomment-830138458
=> refactor(SO Item): Allow description changes on submit

erpnext/patches.txt, erpnext/patches/v12_0/add_mpn_item_linked_date.py
[ISSUE](https://github.com/elexess/eso-next/issues/1392)
[Dependency](https://github.com/elexess/eso-newmatik/pull/4952)
=> fix(Item MPN): Ability to add Date-time to the Item MPN table

erpnext/manufacturing/doctype/bom_item/bom_item.json
In addition to this PR https://github.com/elexess/eso-newmatik/pull/5195
=> refactor(BOM): allow fields in submit for bom alt

erpnext/manufacturing/doctype/bom/bom.js
https://github.com/elexess/eso-newmatik/issues/1244
=> refactor(bom): remove option for pre-defien alternative

erpnext/controllers/accounts_controller.py
https://github.com/elexess/eso-newmatik/issues/5218
1) Allow item_code change.
2) Set other item information like Item Name, description, UOM
3) Set permission validation to only allow Sales Order Manager
4) Set validation to check if the line has already partial delivery then it should not be allowed.
5) Set validation to check if the line has already partial billing then it should not be allowed.
=> refactor(SO,PO): allow update itemcode

erpnext/stock/doctype/material_request_item/material_request_item.json
[Issue Reference](https://github.com/elexess/eso-newmatik/issues/5384#issuecomment-1063761943)
Allowing users to update the Required Date after submitting.
=> fix(material_request_item.json): enabled Allow on Submit for Required date

erpnext/manufacturing/doctype/bom/bom.js, erpnext/manufacturing/doctype/bom/switch_alternative_item.html
re : https://github.com/elexess/eso-newmatik/issues/5414
prerequisite: https://github.com/elexess/eso-newmatik/pull/5478
Dialog box for switching feature if BOM doctype
=> feat(bom doctype): add new dialog for bom line switching

erpnext/manufacturing/doctype/bom_item/bom_item.json
https://app.asana.com/0/1202487840949165/1202550734247279/f
Issue: Can't save BOM its looking for sourced_by_supplier
Solution: Added source_by_supplier in json file
=> feat: added source by supplier field

erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.py
Disable Report Item Valuation Notification
=> refactor(report_item_valuation): Disable Stock Manager Notification

erpnext/manufacturing/doctype/bom/bom.js
- Updated Selected Items Link
- Fixed key error in the anchor tag, changed keyword **targer** to **target**
=> refactor(Bom.js):Fix Selected Item anchor tag link

erpnext/manufacturing/doctype/bom/bom.py
re : https://app.asana.com/0/1202488269220482/1202488935638748
pre-req for : https://github.com/elexess/eso-newmatik/pull/5708
Request: add column in the work order required items to include the locations(assembly references).
=> Refactor(bom)Include locations when creating work order

erpnext/controllers/accounts_controller.py
Asana: https://app.asana.com/0/1202488272591408/1202846909239750
Added validation to fix for updating items in blanket order error  object has no attribute 'update_prevdoc_status'
=> fix(accounts_controller): added validations for update items if blanket order

erpnext/selling/doctype/quotation/quotation.js
pre-req : https://github.com/elexess/eso-newmatik/pull/5756
=> refactor(quotation.js)custom query being overwritten by core code

erpnext/buying/doctype/purchase_order_item/purchase_order_item.json
Asana: https://app.asana.com/0/1202487840949165/1203062221786415
Make supplier part number allow on submit
=> feat(po.json): make supplier_part_no allow on submit

erpnext/stock/doctype/material_request_item/material_request_item.json
This PR is linked to this PR https://github.com/elexess/eso-newmatik/pull/5785
This is for the Update QTY feature in Material Request, we need to be able to edit the qty even after submit so the update qty function will work.
=> refactor(material_request_item.json): Allow on submit qty and stock qty

erpnext/selling/doctype/quotation/quotation.js, erpnext/selling/doctype/quotation/quotation.py
ref : https://app.asana.com/0/1202488269220482/1203427222973689
Feat: Able to create Blanket Orders in Quotation doctype under "Create" Button dropdown.
=> Feat(Quotation)Allow blanket order creation from quotation doctype

erpnext/selling/doctype/sales_order/sales_order.json
ref : https://app.asana.com/0/1202488269220482/1203244682360194
Feat: Allow users to change row index for submitted sales orders by dragging the items in the child table.
Sample:
=> feat(sales_order.json)Allow row changing in childtable by dragging

erpnext/buying/doctype/purchase_order/purchase_order.json
re : https://app.asana.com/0/1202488269220482/1203499496577007
Fix: Allow user to change child table rows for submitted Purchase orders.
Gif:
=> Fix: Allow PO child table rows to be changed

erpnext/controllers/stock_controller.py
[Initial PR Reference](https://github.com/elexess/eso-erpnext/pull/191)
=> fix(stock_controller): Add doctype in validation

erpnext/controllers/stock_controller.py
[Reference Github PR](https://github.com/elexess/eso-erpnext/pull/191)
Added validation for Delivery Note to allow expired batches.
=> fix(stock_controller): add validation for Delivery Note with PCB items

erpnext/stock/doctype/warehouse/warehouse.json
=> Production changes of Warehouse.json

erpnext/hr/doctype/attendance/attendance.py
ref https://app.asana.com/0/1202488269220482/1203898475242988
Feat Req:
--
User wants to create attendances (absences) on future dates. 
Changes:
--
commented out core validation for preventing transaction creation. 
Fix:
--
=> feat(attendance.py):Allow attendance creation for future dates

erpnext/manufacturing/doctype/work_order/work_order.js
ref : https://github.com/elexess/eso-erpnext/commit/1aebcbe7d370f1d6a3b1a9005fdcd828e3f87615
Reverting changes for buttons removal. 
Reason:
-- 
Found custom option, Will be removing via newmatik repository.
=> chore(work_order.js)reverting changes to button removal

erpnext/controllers/accounts_controller.py
ref : https://github.com/elexess/eso-erpnext/pull/201
issue: index error pops up when item's customer detail table is empty.
Fix:
fix if condition.
=> fix(accounts_controller.py)customer items list index error

erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py, erpnext/accounts/utils.py, erpnext/controllers/stock_controller.py, erpnext/stock/__init__.py, erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
Added new function to just retrieve one warehouse data instead of mapping all warehouse
=> fix: replace get_warehouse_account_map

erpnext/stock/get_item_details.py
ref : https://app.asana.com/0/1202488269220482/1204289722402383
feat: select default customer reference from item doctype.
Fix:
--
=> fix(get_item_detail.py):fetch selected customer reference

erpnext/stock/get_item_details.py
ref : https://github.com/elexess/eso-erpnext/pull/209
From failed staging test, looping still going through even when it already found the default value, added break in the loop.
=> fix(get_item_detail.py)fetch customer reference code

erpnext/manufacturing/doctype/bom/bom.js, erpnext/manufacturing/doctype/bom/bom.py, erpnext/manufacturing/doctype/work_order/work_order.js
ref https://app.asana.com/0/1202488269220482/1204437860264087
PR depened in https://github.com/elexess/eso-newmatik/pull/6064
=> fix(Alternative Bom Item)fix linkage of BOM and WO alt items

erpnext/accounts/doctype/sales_invoice/sales_invoice.json
ref https://app.asana.com/0/1202487840949165/1204935408846897/f
Change property of fields to be allow on submit.
fields : ship_to_other_address, customer_address, shipping_address_name
GIF:
https://github.com/elexess/eso-newmatik/pull/6108
=> feat:set propery address fields to allow on submit

erpnext/accounts/doctype/sales_invoice/sales_invoice.json
ref https://app.asana.com/0/1202487840949165/1204935408846897/f
Allow on submit address and contact section in sales invoice
=> fix:sales_invoice.json:Allow on submit address and contact section

erpnext/controllers/accounts_controller.py
Ref: https://github.com/elexess/erp-shipment/pull/145
=> feat(accounts_controller.py): update items in delivery note

erpnext/controllers/accounts_controller.py
ref https://app.asana.com/0/home/1202488269211191/1206640811601531
Allow changing date for Sales order "Update Item" button.
=> feat(accounts_controller.py)allow update item required by date field

erpnext/controllers/accounts_controller.py, erpnext/public/js/utils.js
re https://app.asana.com/0/1202488269220482/1207145452097612
=> feat(utils.js,accounts_controller.py)allow update item feature in delivery note

erpnext/controllers/accounts_controller.py
re: https://app.asana.com/0/home/1202488269211191/1207512847356228
Fix if logic for handling SO and DN update item button.
=> fix(accounts_controller.py)if logic for Delivery Note

erpnext/selling/doctype/quotation/quotation.py
**Asana Task:** [https://app.asana.com/0/1203283251047296/1207479804809163/f](Quotation Status Resets to "Expired")
**Fix:**
Exclude **Won**, **Ordered** and **Cancelled** in function that makes automatic change of status in Quotation
=> fix(quotation.py): quotation status set to expired
