erpnext/manufacturing/doctype/bom/bom.js
Not reported but found it. 
When a empty line is removed and due no "item_code" field throw the error below.
=> Fix if empty BOM Line is removed

erpnext/manufacturing/doctype/bom/bom.py, erpnext/stock/stock_ledger.py
Some indentation fixes I faced during bench migrate, since I am on Python 3.
`TabError: inconsistent use of tabs and spaces in indentation`
=> fix:Indentation fixes for python 3

erpnext/hr/doctype/leave_allocation/leave_allocation.py, erpnext/hr/doctype/leave_ledger_entry/leave_ledger_entry.json
Re: https://github.com/newmatik/newmatik/issues/2758
Added a hook so that whenever the `Total Leaves Allocated ` of `Leave Allocation` is updated, it will also update the `Leaves` on the `Leave Ledger Entry`
=> fix(leave alloc): update ledger leaves after submit

erpnext/hr/doctype/leave_application/leave_application.py
The issue was that on_update was twice, so due to redefinition, only one was being called.
No need to core PR, they have refactored some stuff in develop.
re: https://github.com/newmatik/newmatik/issues/3500
=> fix(Leave Application): Fix approver not being notified

erpnext/hr/doctype/leave_application/leave_application.py
@creamdory The whole culprit is this line of code. Calling create_leave_ledger_entry was causing these issues:
1. Double entry on Approval, 1 because of submitting, another because of update.
2. Even on Reject, it was creating a Leave Ledger which it should not because of calling it on update.
Even in the latest changes refactor from the core, it has been removed. 
Now we only have to correct the existing data.
re: https://github.com/newmatik/newmatik/issues/3486
=> fix(leave_app): Do not update Leave Ledger on update

erpnext/projects/doctype/timesheet/timesheet.js
Removed a part of the code where it is getting the `standard_working_hours` from Company doctype. This results into an error since `standard_working_hours` has been removed with this PR from core https://github.com/frappe/erpnext/pull/22400.
=> fix(timesheet): remove company's standard_working_hours

erpnext/accounts/general_ledger.py
Findings so far:
- It turns out Stock Entry Submit is slow for certain type of Stock Entries, even if it from direct Stock Entry.
- If we leave it at Draft it is fine, it is the Submit.
- There are lots of validations and updates that happen on Submit of Stock Entry.
- I drilled down to each one of it and figured the one causing slow down is make_gl_entries.
- Under make_gl_entries there are another set of validations and entries that happen.
- Again had to drill down., came to validate_account_for_perpetual_inventory in General ledger.
- Even though it is not used in version-12, half of the code is commented out from core, this half developed method exists.
- In version-13 it is fixed. But I still doubt that our problem will be solved or not.
- it goes down to method called …
=> fix(Tools): Remove perpetual entry validation

erpnext/manufacturing/doctype/blanket_order/blanket_order.js
[Issue](https://github.com/elexess/eso-newmatik/issues/4898)
=> fix(blanket_order.js): onlick 'View Orders' now filters using Sales Order Item for Blanket Order

erpnext/stock/doctype/control_band/control_band.json, erpnext/stock/doctype/ghs_hazard_statement/ghs_hazard_statement.py, erpnext/stock/doctype/hazardous_material/hazardous_material.py
[issue#4769](https://github.com/elexess/eso-newmatik/issues/4769)
**Item:**
- Added Field "Is Hazardous Material" as is_hazardous_material
- Added Field "Is Personal Protective Equipment (PPE)" as is_ppe
**Filter Item Selection**
- In "Hazardous Material" filter "Item" by item.is_hazardous_material = true
-  In "Control Band" filter "Item" by item.is_ppe = true
**Hazardous Material**
- if "lifecycle" -> "Decommissioned" is selected the Decommissioning Date must be set first.
- If "lifecycle" -> "Active use" is selected the Introduction Date must be set first.
- Make color of "Status" as follows: Draft = red, For Approval = yellow, Approved = green, Review = yellow
- When adding a "GHS Hazard Statement" in the Child Table -> add all the preset "GHS Precautionary Statements" from the "GHS …
=> feat(Hazardous Material): Hazardous Material Features

erpnext/stock/doctype/stock_entry/stock_entry.py
re : https://github.com/elexess/eso-newmatik/issues/5327
Issue:
When declaring "Finish" to a partially created Work Order, the remaining quantities need to create the Work Order are not correctly being fetched. Instead, it double books the quantities required in the stock entry.
Changes:
Fixed the logic for fetching the quantities for the created SE.
WO:
SE:
=> fix(work order): fix logic of fetching qty for SE manufacture type if WO is partially finished

erpnext/controllers/accounts_controller.py
[Issue](https://github.com/elexess/eso-newmatik/issues/5484)
The cause of the error is that in Blanket Order whenever you update an item the object that is being passed doesn't have a 'billed_amt' so with that I added a filter to also check if the object contains a "billed_amt" key.
=> feat: added filter to check if a key exist in dict

erpnext/manufacturing/doctype/bom/bom.js, erpnext/manufacturing/doctype/bom/switch_alternative_item.html
re : https://github.com/elexess/eso-newmatik/issues/5414
remove original bom in alternative bom item options
=> fix: (bom) hide "switch_to_alternative_item" button if there are no altenative options.

erpnext/manufacturing/doctype/bom/bom.js
re : https://github.com/elexess/eso-newmatik/issues/5414
Issue: 
the field : selected alternative items are not switching when the alternative bom is switched.
Expected:
the selected alt items should switch to that of the current item being used in the bom line.
Results:
--
=> fix(bom): change options for selected_alt_items field when switching bom

erpnext/manufacturing/doctype/bom/bom.js
re : https://github.com/elexess/eso-newmatik/issues/5504
Description:
selected bom lines are disappearing when clicking on "setup_alt_item_btn"
Result:
=> BOM(fix): Alternative Boms disappearing when setting up alt boms

erpnext/controllers/accounts_controller.py, erpnext/public/js/utils.js
This was supposed to be PR to erpnext but it was closed by Ankush
**WHATS in the PR:**
1. Added back the Reqd By Date in Sales Order and Sales Order Item Doctype
2. Added back the Reqd By Date column in Update Items Dialog
=> feat: added the required by date

erpnext/stock/doctype/stock_entry/stock_entry.py
re: https://github.com/elexess/eso-newmatik/issues/5568
Issue: When clicking finish for partially manufactured Work Order, it pull all the required quantities for the Stock Entry. 
Fix: It should only pull the quantities required.
Result:
=> fix(Work Order): fix finish button issue not fetching correct quantities

erpnext/controllers/accounts_controller.py, erpnext/public/js/utils.js
Issue:
Error: Sales Order Item Row #4: Value missing for: Reqd By Date
Solution:
In the previous version, we have customized the sales order time and added the required date. Now what happens in the error, it's looking for the required date to pass to the items table. It won't let it pass without the required, as this field is mandatory.
To fix this we have to add a required data field inside the dialog box and pass the data to the items table on update.
Screenshot:
Before:
After:
=> fix(Sales Order Item): Add Required Date

erpnext/buying/doctype/purchase_order_item/purchase_order_item.json
https://app.asana.com/0/1202487840949165/1202689071891911/f
Issue:
Once a PO is in the status "sent" or "order confirmed" you cannot change the description field anymore. This was a special feature that used to work in the previous ERPNext instance. We need to be able to adjust the description at any time in the PO workflow process.
Solution:
Allow on submit, description field in purchase order item
Before:
After:
=> refactor(Purchase order item): Allow on Submit Description Field

erpnext/controllers/accounts_controller.py
Asana Link: https://app.asana.com/0/1202488272591408/1202674240348232
Investigation Result:
As I was checking on this issue I found out that in v13 frappe added a validation to not allow 0 qty. So, I checked our v12 code, we don't have those validations. So before, frappe really don't have these validations they just added it last May 11 you can refer to this commit from frappe https://github.com/frappe/erpnext/commit/56478752e4eb0572ef50a5b713d6b905ba9951b3
Solution:
As discussed in the Asana, we will be commenting out the added validation.
Additional:
As I was checking our v12 coded we're missing condition for blanket order, so I also added it in this PR
=> feat: commented the validation for zero qty in PO

erpnext/selling/doctype/sales_order_item/sales_order_item.json
Asana: https://app.asana.com/0/1202487840949165/1202711935394143/f
Issue: users can't update the Item Description in Sales Orders after submit
Solution: Allow on submit description field
Before:
After:
=> (Sales Order): Allow on submit description field

erpnext/manufacturing/doctype/work_order/work_order.js
re : https://app.asana.com/0/1202488269220482/1202714014769535
Issue:
Added function in version-13 updates the quantity to 1. when using the switch item feature, item's required quantity should be the same after switching.
Fix:
How to test:
1. Go to work order doctype.
2. Select a work order with alternative items
3. switch item with alternative item
Expected behavior:
required quantity should be the same as original item.
=> Fix(Work Order):remove v13 function causing alt item qty to update to 1

erpnext/manufacturing/doctype/bom/alternative_items_selector.html, erpnext/manufacturing/doctype/bom/switch_alternative_item.html, erpnext/manufacturing/doctype/work_order/alternative_items_selector.html
reported via MS teams by @jeremythegreat01 
Issue: Icons in the switch alternative item feature not being displayed
Problem: This is due to migration to version-13. previously frappe version-12 used glyphicons as its icon's library. In version-13 it was changed to font-awesome.
Fix:
BOM Doctype
--
Work Order Doctype
--
=> Fix:(Switch Alt item feature)Icon buttons not being displayed

erpnext/manufacturing/doctype/bom/bom.js
No asana task 
Issue: When changing the quantity of the alternative item, it doesn't apply the changes when it is done on the second time.
Fix:
=> Fix(BOM):BOM switch alt item not changing quantity on send attempt

erpnext/selling/doctype/quotation/quotation.json
re : No asana task. error found will invetigation on quotaiton doctype.
Issue: valid till date is not editable after submit
Fix: Change property of valid_till date "allow on submit" to be true.
=> Fix(Quotation):valid_till date should be editable even after submit

erpnext/hooks.py
Asana Link: https://app.asana.com/0/1202487840949165/1202804825411024/f
Problem:
Es können keine Zahlungen gebucht werden
Solution:
So in version-13 there is an existing python file called dunning, inside here there's a function that we're calling on submit in payment terms that checks the reference sales invoices inside that PT and get the list of all dunning that is link to those sales invoices and set its value to resolved
now what's going on is when it calls that function it sets its status to resolved, and here's where the problem is our dunning doesn't have a field called status that has resolved and unresolved option
when it sets it, it triggers the problem
but for payment terms that doesn't have sales invoice references this works, and we can easily submit.
=> refactor(Hooks): Remove Core Dunning Function Call

erpnext/controllers/accounts_controller.py
re : https://app.asana.com/0/1202488269220482/1202846633911274/1202768401338209
Issue: unable to add item using update item code because it's looking for req_by_date field. The Req By Date field is only used in Sales Order. Since Purchase Order already has a Request by date field, but it's field name is "schedule_date"
Fix:
--
=> Fix(accounts_controller)Unable to add item_code using Update item

erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py, erpnext/accounts/doctype/sales_invoice/sales_invoice.py
Asana: https://app.asana.com/0/1202487840949165/1202960961234555/f
Issue:
Tanja could not create a purchase invoice for purchase order [PO-DE-22-02155](https://erp.eso-electronic.com/app/purchase-order/PO-DE-22-02155) because of an error message.
Screenshot:
Fix: There is a new validation in erpnext v13 that won't allow if the default currency and the currency used is equal to 1. Which in this case the EUR and USD where there are times these two are equal.
Screenshot:
=> fix(Purchase Invoice): Conversion Rate Cannot be 1|0

erpnext/manufacturing/doctype/bom/bom.js
re : https://app.asana.com/0/1202488269220482/1203003479717830
Created as a sub issue. 
Issue: incorrect links for alternative items
Fix:
=> Fix(BOM)missing "/" in link when creating alternative items

erpnext/buying/doctype/purchase_order_item/purchase_order_item.json
Asana: https://app.asana.com/0/1202488272591408/1203034306486826/f
Making the supplier part number visible and mandatory. Doing it in the core since it doesn't allow me to make it unhidden using customize form
=> feat(po.json): maked the supplier part no visible and mandatory

erpnext/buying/doctype/purchase_order_item/purchase_order_item.json
Making the supplier part nonmandatory cos it causes an error to the functions that create PO or add items in PO
=> fix(po.json): make nonmandatory the supplier part number

erpnext/buying/doctype/request_for_quotation/request_for_quotation.py
Upon submitting a request for quotation, an error occur see screenshot below
Upon investigation, it is because of missing gender in creating user for supplier but as discussed in MS Teams, to comment the code for creating user for supplier in creating request for quotation
=> feat(request_for_quotation.py): commented the code for creating user for supplier

erpnext/hr/doctype/leave_allocation/leave_allocation.json
re : https://app.asana.com/0/1202488269220482/1203175074079541
Request: Set field properties for carry_foward and unsused leaves to be allowed_on_submit
Fix:
--
=> fix(leave allocation)set carry_forward and unused_leaves to allowed_on_submit

erpnext/hr/doctype/leave_ledger_entry/leave_ledger_entry.json
re : https://app.asana.com/0/1202488269220482/1203175074079541
Issue noticed when testing:
https://github.com/elexess/eso-erpnext/pull/183
When ticking the "add unused leaves..." it saves successfully. But when reverting it back to unchecked, it throws the not allowed on submit error. 
Error:
This is because there's another field in a different doctype (Leave Ledger Entry) being changed.
Fix: set the property of that field (leave) to be allowed on submit.
--
=> fix(leave_ledger_entry.json)set allow_on_submit property leave field

erpnext/manufacturing/doctype/work_order/work_order.js
Ref: https://app.asana.com/0/1202487840949165/1203503802585335/f
Issue: 
Some alternative items in Work Order show duplicate item when switching. 
Solution: 
Filter duplicates with same alt item then remove.
=> fix(work_order.js): duplicate alternative items when switching

erpnext/controllers/stock_controller.py
Reference [Asana Link](https://app.asana.com/0/1202487840949165/1203578072994970/f)
**Solution:** Allow Material Transfers with Expired Batches for Items that belong to PCB (Leiterplatten) and PCB (Leiterplatten) - Customer provided for scrapping purposes.
See attached video below as a reference:
https://user-images.githubusercontent.com/58759735/208585210-a6d40229-2723-46ab-a915-a366efdeec41.mp4
=> fix(stock_controller): allow expired batches for Material Transfers with PCB item groups

erpnext/manufacturing/doctype/work_order/work_order.js
Ref : https://app.asana.com/0/1202488269220482/1203819087538970
remove core close buttons in work order doctype.
before:
after:
=> chore(work_order.js)remove core close button

erpnext/hooks.py
Remove scheduled events in ERPNext hooks that rename both `GLE` and `SLE` we will be using instead the hash name that being set automatically when we create GLE and SLE.
This will solve the Lock wait Timeout we are encountering.
- **How does it resolve the issue:**
- Bulk-updating existing transactions especially for GL Entries and SL Entries can be a heavy operation.
- So, instead of waiting every 30 minutes to update all created Stock Entries to their related GL entries and SL entries, the updated naming will allow us to directly connect the transactions to each other.
- Thus, this will also reduce the overall update time required in renaming the connected GL Entries and SL Entries to the Stock Entry, which is currently scheduled every 30 minutes.
=> feat(hooks.py): comment cruns update_youtube_data, rename_gle_sle_doc, reorder_item

erpnext/hr/doctype/leave_application/leave_application.py
-----
Reference: [Asana Link](https://app.asana.com/0/1202487840949165/1204175061824967/f)
**Solution:** Removed filter for Leave Type Field to show all Leave Types
Attached image as a sample:
=> fix(leave_application.py) remove is_lwp condition

erpnext/public/js/utils.js
Asana: https://app.asana.com/0/1202487840949165/1204201602052788/f
Issue:
Update Items button in Purchase Order is not clickable because of the `ReferenceError: dialog is not defined` 
Solution:
Declare `dialog` variable.
Result:
=> fix(utils.js): Update Items btn dialog variable assignment

erpnext/hr/doctype/leave_application/leave_application.py
ref : https://app.asana.com/0/1202488269220482/1204257506305355
Issue: Incorrect allocated leaves being displayed when creating a leave application. ERPNEXT core added changes in the script that considers "expired leaves" so it considers the leaves from previous years. In this case ESO doesn't have "expired_leaves" so we will be reverting their code changes.
Fix:
**from reported user leave application**
=> fix(leave_application.py):fix incorrect available leaves being displayed

erpnext/manufacturing/doctype/work_order/work_order.js
Asana Link: https://app.asana.com/0/1202487840949165/1204528939880890/f
Problem: Users often cannot see the workflow state when in the work order. 
Solution: Add Material Consumption Button to Create Group
Screenshot:
Before:
After:
=> fix(work_order.js): Add Material Consumption Button to Create Group

erpnext/controllers/accounts_controller.py
Ref: https://github.com/elexess/erp-shipment/pull/145#issuecomment-1678673118
Error: 
Fix: 
Delivery note uses the posting date instead of transaction date. With this, set a value for the transaction date with posting date only for Delivery Note doctype
=> fix(accounts_controller): attributeerror transaction date

erpnext/controllers/accounts_controller.py
ref : https://app.asana.com/0/1202487840949165/1206703849302926
Issue:
--
When the "Update Tracking and Cost" button is pressed in [SHIPMENT-03469](https://erp.eso-electronic.com/app/shipment/SHIPMENT-03469), an UnboundLocalError is encountered.
UnboundLocalError: local variable 'reqd_prev_date' referenced before assignment
Fix:
--
reqd_prev_date field is not being used in Shipments, added a condition to use this field only if parent_doctype is Sales Order
=> fix(accounts_controller)error when updaing DN status
